@startuml
'https://plantuml.com/class-diagram
Main -> Restaurante :agregarArticuloEnPedido(idCliente:String, codigoArticulo: String): void
activate Restaurante
 Restaurante -> Restaurante: buscarCliente(idCliente: String): Cliente
    alt cliente existe
        loop por cada cliente
            activate Restaurante
            Restaurante -> Cliente: soyCliente(idCliente: String): boolean
                activate Cliente
                    Restaurante <-- Cliente:  boolean
                deactivate Cliente
        end
    else cliente no existe
        Restaurante --> Main: trowExeption
    end
    alt tiene menos de 2 pedidos pendientes
        Restaurante -> Cliente: menosDeDosPendies(): boolean
            activate Cliente
            Restaurante <-- Cliente:  boolean
            deactivate Cliente
        deactivate Restaurante
    else  no puede puedeRealizarPedido
    Restaurante --> Main: trowExeption
    end
     Restaurante -> Restaurante: buscarProducto(codigoArticulo: String): Producto
     alt el producto existe
            loop por cada Producto
                activate Restaurante
                Restaurante -> Producto: soyProducto(idProducto): boolean
                    activate Producto
                        Restaurante <-- Producto:  boolean
                    deactivate Producto
                deactivate Restaurante
            end
        else no se encontro el Producto
        Restaurante --> Main: trowExeption
        end
         alt no tiene productos de la misma categoria
                Restaurante -> Cliente: productosMismaCategoria(producto Producto): boolean
                    activate Cliente
                    Restaurante <-- Cliente:  boolean
                    deactivate Cliente


            else no puede puedeRealizarPedido
            Restaurante --> Main: trowExeption
            end
             Restaurante -> Cliente: agregarPedidosPendientes():Pedido
                     activate Cliente
                     Cliente -> Pedido: Pedido(producto Producto)

                     activate Pedido
                     Pedido -->Cliente: Pedido
                     deactivate Pedido
                     Cliente --> Restaurante: Pedido
                     deactivate Cliente
                     Restaurante -> Restaurante: confrimarPedido(pedido Pedido): void
                     Restaurante --> Main: Void

deactivate Restaurante
@enduml