@startuml
'https://plantuml.com/class-diagram
Main -> Restaurante :mostrarPrecioPedido(idCliente: String,idPedido: String, cantidad: double): double
activate Restaurante
 Restaurante -> Restaurante: buscarCliente(idCliente: String): Cliente
            Restaurante -> Cliente: tengoElPedido(idPedido: String):boolean
             activate Cliente
                                Restaurante <-- Cliente:  boolean
             deactivate Cliente
    alt existe pedido
            loop por cada pedido pendiente
            Restaurante -> Cliente:  buscarEnPedidosPendientes(idPedido: String): Pedido
            activate Cliente
            Cliente --> Restaurante : Pedido
            deactivate Cliente
            end
    Restaurante -> Producto: mostrarPrecio(cantidad double): double
    activate Producto

    deactivate Producto
    else clienteNoExiste
        Restaurante --> Main: trowExeption
    end


deactivate Restaurante
@enduml