@startuml
'https://plantuml.com/class-diagram
Main -> Biblioteca :cotizarPrestamo( idEstudiante: String, codigoDeMaterial: String, fechaDevolucion: int): void
activate Biblioteca
 Biblioteca -> Biblioteca: buscarEstudiante(idEstudiante: String): Estudiante
    alt estudiante existe

        loop por cada estudiante

            activate Biblioteca
            Biblioteca -> Estudiante:  sosEstudiante(idEstudiante: String):boolean
                activate Estudiante
                    Estudiante -> TarjetaBiblioteca: mostrarId(): String
                    activate TarjetaBiblioteca
                    TarjetaBiblioteca --> Estudiante: String
                    deactivate TarjetaBiblioteca
                    Biblioteca <-- Estudiante:  boolean
                deactivate Estudiante
            deactivate Biblioteca
        end

    else no se encontro el estudiante
    Biblioteca --> Main: trowExeption
    end
deactivate Biblioteca
@enduml